### ISSUE TITLE
Configuration manager json save is broken in PHP 7

### ISSUE THREAD

**Issue by adanielvv** [Project60/org.project60.banking#181]

**Comment by bkaless** [comment]
Perhaps this issue means, that processing of payments doesn't work.

**Comment by DanielvV** [comment]
No. This issue means that you can't save the json value in the new configuration manager in php 7.
I created #187 for the payment processing issue.

**Comment by danielvv** [comment]
Is fixed in current master. This issue can be closed when 0.6 is out I guess.

**Comment by adanielvv** [comment]
0.6 is out!

**Comment by jaapjansma** [comment]
I still have this issue on a php 7.0.30 and banking version 0.7-aplha2 and the master branch

**Comment by jaapjansma** [comment]
I am sorry it was a misconfiguration of the server. Which looked up an older version of banking. I will close this issue.
