### ISSUE TITLE
This plugin requires class CRM_Banking_PluginImpl_Matcher_AutoMultiContribution which does not seem to exist.

### ISSUE THREAD

**Issue by stijndmd** [Project60/org.project60.banking#186]
Hi

I have updated locally to CiviCRM 4.7.28 and to Banking 0.5.3.

Uploading a file to test import results in:

"This plugin requires class CRM_Banking_PluginImpl_Matcher_AutoMultiContribution which does not seem to exist."

```
Jan 11 11:04:21  [info] $backTrace = #0 /var/www/vvog/sites/all/modules/civicrm/CRM/Core/Error.php(336): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 /var/www/vvog/sites/all/civicrm/extensions/org.project60.banking-master/extension/CRM/Banking/BAO/PluginInstance.php(111): CRM_Core_Error::fatal("This plugin requires class CRM_Banking_PluginImpl_Matcher_AutoMultiContributi...")
#2 /var/www/vvog/sites/all/civicrm/extensions/org.project60.banking-master/extension/CRM/Banking/BAO/PluginInstance.php(120): CRM_Banking_BAO_PluginInstance->getClass()
#3 /var/www/vvog/sites/all/civicrm/extensions/org.project60.banking-master/extension/CRM/Banking/Matcher/Engine.php(76): CRM_Banking_BAO_PluginInstance->getInstance()
#4 /var/www/vvog/sites/all/civicrm/extensions/org.project60.banking-master/extension/CRM/Banking/Matcher/Engine.php(53): CRM_Banking_Matcher_Engine->initPlugins()
#5 /var/www/vvog/sites/all/civicrm/extensions/org.project60.banking-master/extension/CRM/Banking/Matcher/Engine.php(37): CRM_Banking_Matcher_Engine->init()
#6 /var/www/vvog/sites/all/civicrm/extensions/org.project60.banking-master/extension/api/v3/BankingTransaction.php(170): CRM_Banking_Matcher_Engine::getInstance()
#7 /var/www/vvog/sites/all/modules/civicrm/Civi/API/Provider/MagicFunctionProvider.php(89): civicrm_api3_banking_transaction_analyselist((Array:5))
#8 /var/www/vvog/sites/all/modules/civicrm/Civi/API/Kernel.php(169): Civi\API\Provider\MagicFunctionProvider->invoke((Array:9))
#9 /var/www/vvog/sites/all/modules/civicrm/Civi/API/Kernel.php(100): Civi\API\Kernel->runRequest((Array:7))
#10 /var/www/vvog/sites/all/modules/civicrm/api/api.php(23): Civi\API\Kernel->runSafe("BankingTransaction", "analyselist", (Array:5), NULL)
#11 /var/www/vvog/sites/all/modules/civicrm/CRM/Utils/REST.php(404): civicrm_api("BankingTransaction", "analyselist", (Array:5))
#12 /var/www/vvog/sites/all/modules/civicrm/CRM/Utils/REST.php(641): CRM_Utils_REST::process((Array:3), (Array:3))
#13 [internal function](): CRM_Utils_REST::ajax()
#14 /var/www/vvog/sites/all/modules/civicrm/CRM/Core/Invoke.php(275): call_user_func((Array:2))
#15 /var/www/vvog/sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:12))
#16 /var/www/vvog/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3))
#17 /var/www/vvog/sites/all/modules/civicrm/drupal/civicrm.module(448): CRM_Core_Invoke::invoke((Array:3))
#18 [internal function](): civicrm_invoke("ajax", "rest")
#19 /var/www/vvog/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:2))
#20 /var/www/vvog/index.php(21): menu_execute_active_handler()
#21 {main}
```

What am I missing here?

**Comment by stijndmd** [comment]
Also, I can only turn on the extenstion in the database.
When I try to do it via the config page I get: 

"CiviCRM_API3_Exception: "Could not find the SQL file."

```
#0 /var/www/vvog/sites/all/modules/civicrm/CRM/Admin/Form/Extensions.php(195): civicrm_api3("Extension", "enable", (Array:1))
#1 /var/www/vvog/sites/all/modules/civicrm/CRM/Core/Form.php(447): CRM_Admin_Form_Extensions->postProcess()
#2 /var/www/vvog/sites/all/modules/civicrm/CRM/Core/StateMachine.php(160): CRM_Core_Form->mainProcess()
#3 /var/www/vvog/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Next.php(61): CRM_Core_StateMachine->perform(Object(CRM_Admin_Form_Extensions), "next", "Next")
#4 /var/www/vvog/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Next->perform(Object(CRM_Admin_Form_Extensions), "next")
#5 /var/www/vvog/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Admin_Form_Extensions), "next")
#6 /var/www/vvog/sites/all/modules/civicrm/CRM/Core/Controller.php(351): HTML_QuickForm_Page->handle("next")
#7 /var/www/vvog/sites/all/modules/civicrm/CRM/Core/Page/Basic.php(398): CRM_Core_Controller->run()
#8 /var/www/vvog/sites/all/modules/civicrm/CRM/Core/Page/Basic.php(156): CRM_Core_Page_Basic->edit(32, NULL)
#9 /var/www/vvog/sites/all/modules/civicrm/CRM/Admin/Page/Extensions.php(121): CRM_Core_Page_Basic->run()
#10 /var/www/vvog/sites/all/modules/civicrm/CRM/Core/Invoke.php(309): CRM_Admin_Page_Extensions->run((Array:3), NULL)
#11 /var/www/vvog/sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:16))
#12 /var/www/vvog/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3))
#13 /var/www/vvog/sites/all/modules/civicrm/drupal/civicrm.module(448): CRM_Core_Invoke::invoke((Array:3))
#14 [internal function](): civicrm_invoke("admin", "extensions")
#15 /var/www/vvog/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:2))
#16 /var/www/vvog/index.php(21): menu_execute_active_handler()
#17 {main}
```

**Comment by DanielvV** [comment]
@stijndmd Installation of CiviBanking up to version 0.5.3 stopped working from CiviCRM version 4.7.20 and upwards. See #175.
This is fixed in the latest [prerelease, 0.6.alpha1](https://github.com/Project60/org.project60.banking/releases). About the other error, I think it is because the SQL file was not installed...

**Comment by stijndmd** [comment]
Alrighty.


I have updated now to 0.6.alpha1. Enabling now works fine, but the error I get after uploading an import file is still the same from my OP:

```
Jan 11 11:04:21  [info] $backTrace = #0 /var/www/vvog/sites/all/modules/civicrm/CRM/Core/Error.php(336): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 /var/www/vvog/sites/all/civicrm/extensions/org.project60.banking-master/extension/CRM/Banking/BAO/PluginInstance.php(111): CRM_Core_Error::fatal("This plugin requires class CRM_Banking_PluginImpl_Matcher_AutoMultiContributi...")
#2 /var/www/vvog/sites/all/civicrm/extensions/org.project60.banking-master/extension/CRM/Banking/BAO/PluginInstance.php(120): CRM_Banking_BAO_PluginInstance->getClass()
#3 /var/www/vvog/sites/all/civicrm/extensions/org.project60.banking-master/extension/CRM/Banking/Matcher/Engine.php(76): CRM_Banking_BAO_PluginInstance->getInstance()
#4 /var/www/vvog/sites/all/civicrm/extensions/org.project60.banking-master/extension/CRM/Banking/Matcher/Engine.php(53): CRM_Banking_Matcher_Engine->initPlugins()
#5 /var/www/vvog/sites/all/civicrm/extensions/org.project60.banking-master/extension/CRM/Banking/Matcher/Engine.php(37): CRM_Banking_Matcher_Engine->init()
#6 /var/www/vvog/sites/all/civicrm/extensions/org.project60.banking-master/extension/api/v3/BankingTransaction.php(170): CRM_Banking_Matcher_Engine::getInstance()
#7 /var/www/vvog/sites/all/modules/civicrm/Civi/API/Provider/MagicFunctionProvider.php(89): civicrm_api3_banking_transaction_analyselist((Array:5))
#8 /var/www/vvog/sites/all/modules/civicrm/Civi/API/Kernel.php(169): Civi\API\Provider\MagicFunctionProvider->invoke((Array:9))
#9 /var/www/vvog/sites/all/modules/civicrm/Civi/API/Kernel.php(100): Civi\API\Kernel->runRequest((Array:7))
#10 /var/www/vvog/sites/all/modules/civicrm/api/api.php(23): Civi\API\Kernel->runSafe("BankingTransaction", "analyselist", (Array:5), NULL)
#11 /var/www/vvog/sites/all/modules/civicrm/CRM/Utils/REST.php(404): civicrm_api("BankingTransaction", "analyselist", (Array:5))
#12 /var/www/vvog/sites/all/modules/civicrm/CRM/Utils/REST.php(641): CRM_Utils_REST::process((Array:3), (Array:3))
#13 [internal function](): CRM_Utils_REST::ajax()
#14 /var/www/vvog/sites/all/modules/civicrm/CRM/Core/Invoke.php(275): call_user_func((Array:2))
#15 /var/www/vvog/sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:12))
#16 /var/www/vvog/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3))
#17 /var/www/vvog/sites/all/modules/civicrm/drupal/civicrm.module(448): CRM_Core_Invoke::invoke((Array:3))
#18 [internal function](): civicrm_invoke("ajax", "rest")
#19 /var/www/vvog/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:2))
#20 /var/www/vvog/index.php(21): menu_execute_active_handler()
#21 {main}
```

**Comment by DanielvV** [comment]
Ok, I see. Did you configure CiviBanking as per https://github.com/Project60/org.project60.banking/wiki ?

The AutoMultiContribution matcher does not exist.
See https://github.com/Project60/org.project60.banking/blob/master/doc/civibanking-getting-started.md#configuring-plugins

In the latest prerelease (the one you just installed) there is a GUI for configuring plugins, whi.
It currently does not work with php 7: #181, but it does with php 5.

**Comment by stijndmd** [comment]
I still have the plugins we used. The settings look kinda empty now:

<img width="1305" alt="screen shot 2018-01-11 at 12 49 45" src="https://user-images.githubusercontent.com/2393272/34824251-f61ae84e-f6cd-11e7-9aca-95c7cc7bc05f.png">

**Comment by stijndmd** [comment]
So the plugin we have setup (legacy) for this import used "extension/CRM/Banking/PluginImpl/Matcher/AutoMultiContribution.php" but that file was removed in the update.

I have to setup a plugin from scratch then?

**Comment by DanielvV** [comment]
How did you get that file there?
Was it part of some previous version of CiviBanking?

Or is it a custom addition?
If so, you could try to put the file there again manually.

About the plugin settings in the GUI, this is my screen:
![afbeelding](https://user-images.githubusercontent.com/9696905/34828439-d8520e7c-f6dd-11e7-9f63-1846e5233446.png)

**Comment by stijndmd** [comment]
I have placed the following 3 files back in /org.project60.banking-master/extension/CRM/Banking/PluginImpl/Matcher:

* AutoMultiContribution.php
* NameMatcher.php
* RizivMatcher.php

I have checked this extension back to version 0.5 and there is no trace of these files in that version. Somehow, the 0.5.2 that is running on the production site has these files / classes.
They could have been placed there by a legacy developer without proper patch notes to failsafe future updates, but then again, the files all start with:

```
<?php
/*-------------------------------------------------------+
| Project 60 - CiviBanking                               |
| Copyright (C) 2013-2014 SYSTOPIA                       |
| Author: B. Endres (endres -at- systopia.de)            |
| http://www.systopia.de/                                |
+--------------------------------------------------------+
| This program is released as free software under the    |
| Affero GPL v3 license. You can redistribute it and/or  |
| modify it under the terms of this license which you    |
| can read by viewing the included agpl.txt or online    |
| at www.gnu.org/licenses/agpl.html. Removal of this     |
| copyright header is strictly prohibited without        |
| written permission from the original author(s).        |
+--------------------------------------------------------*/
```

Either way, the importer is up and running now on my local install.

**Comment by DanielvV** [comment]
Curious. But glad that it works again.

@systopia manages this extension, so maybe he knows...

**Comment by stijndmd** [comment]
Oh and is the 0.6 alpha compatible with old versions of civicrm (4.6.16)?

**Comment by DanielvV** [comment]
Think so. Didn't hear otherwise.

But with alpha versions nothing is guaranteed...

**Comment by DanielvV** [comment]
I think its not advisable to use alpha versions in production. (Not that I don't do that).

4.6.34 is the latest LTS version of CiviCRM.
I think using Banking 0.5.3 with that is a better idea.

**Comment by stijndmd** [comment]
It is not advisable but I need to use when I want to push the civicrm update live :)

So yeah there's that.

**Comment by systopia** [comment]
Hi guys. Happy to see such a lively discussion :)

The three custom matchers (AutoMultiContribution, NameMatcher and RizivMatcher) are defintely not from me and were never part of any official CiviBanking release. I assume some other developer just copied one of my files and forgot to change the header.

The current ``0.6 alpha`` version has quite a lot of new developments that should make your live a lot easier, and it seems to work well on 4.6.x. Seeing that you, as I understand, have to test the setup thoroughly anyway, I would go for 0.6.

**Comment by stijndmd** [comment]
Some proper legacy fun times :)

I will go for 0.6 on production when the client approved this new build. Will keep you posted if more issues should come to surface.

**Comment by kewljuice** [comment]
Hi @stijndmd,

I'am the legacy/other developer, I forgot to change the header from the original CiviCRM banking files, I recently used these matcher(s) on 0.6.  I've created an extension with these matchers and some documentation: https://github.com/kewljuice/be.ctrl.banker

**Comment by systopia** [comment]
Thanks for sharing @stijndmd !
